### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by fabiowaga** [jczic/ESP32-MPY-Jama#14]
Hi

Some antiviruses are triggering alerts to the installer. Has anyone else noticed this?

![ps](https://user-images.githubusercontent.com/39389005/217692188-cdb24888-a554-4610-858b-ee424b899b4a.png)

**Comment by jczic** [comment]
Hello @fabiowaga and thank you for the feedback.
Yes, I know that and I'm searching the problem with some generic malwares detected.

**Comment by jczic** [comment]
You can check : https://github.com/pyinstaller/pyinstaller/issues/5854
I use PyInstaller too 👍🏻 
The next version will not be detected I think.
