### ISSUE TITLE
not connect to my esp32

### ISSUE THREAD

**Issue by shaondoc** [jczic/ESP32-MPY-Jama#21]
maximum times it showed unable to connect

**Comment by jczic** [comment]
Hi @shaondoc, could you check this issue please -> https://github.com/jczic/ESP32-MPY-Jama/issues/11

**Comment by jczic** [comment]
@shaondoc, I may have fixed the problem but for the moment it is not in a binary release but only in the latest git sources.
Check again the issue : https://github.com/jczic/ESP32-MPY-Jama/issues/11 if you want. Thank you :)

**Comment by jczic** [comment]
@shaondoc, I just corrected the problem normally!
If you want, you can try again and confirm me?
However, it's not yet in the MacOS and Windows binaries, you have to clone the repository and run it from the sources.
