### ISSUE TITLE
Saving of Wi-Fi configuration not working

### ISSUE THREAD

**Issue by happenpappen** [jczic/ESP32-MPY-Jama#31]
I tried several ways to safe the Wi-Fi configuration, but all end in errors:

1. Directly after starting the program and connecting a device click on the "Connect Wi-Fi" button in the left sidebar. After connection to the Wi-Fi is established, change to the "Networks" view and click on the save button. After this action the "System", "Networks" and "Connect Wi-Fi" and "Firmware Tools" buttons in the sidebar and the "Disconnect device" button in the top right don't work anymore - you can click them, but nothing happens.
2. After starting the program and connecting a device click on "Networks" in the sidebar and then the "config" link. Then proceed as in 1.

I tested this on Linux using the current version from git with a "Seeed Studio XIAO ESP32C3" board.

**Comment by jczic** [comment]
Hi @happenpappen, hmm, could you try in the REPL to enter "from esp32 import NVS" and see if it works correctly?
The configuration backup saves settings in the non-volatile NVS partition via the esp32.NVS module.
In addition, it creates a file "_jamaBootCfg.py" in the root of the Flash and adds a line in boot.py to load it.
Do you see this file created in your Flash?

**Comment by happenpappen** [comment]
I fetched the current sources this morning and now it's working again - so it looks like the fix is working. And yes, i test with the current 1.19.1 Micropython version.
