### ISSUE TITLE
Dialogs should accept "Enter" and "ESC" keys

### ISSUE THREAD

**Issue by happenpappen** [jczic/ESP32-MPY-Jama#32]
For improved usability: Dialogs should accept pressing the "Enter" key instead of "OK" and the "ESC" key instead of "Cancel".

**Comment by jczic** [comment]
@happenpappen , yes I know, I often think about it but I haven't done it yet, it would indeed be more practical to use on the dialog boxes :)
( On the other hand, I improved the use of some keys on the little IDE, especially with TAB and shift+TAB ).

**Comment by jczic** [comment]
I just added key ESC to close dialogue boxes for the moment :)

**Comment by jczic** [comment]
I also added the ENTER key to validate dialogue boxes.

**Comment by happenpappen** [comment]
Cool, looks good! Thank you!
