### ISSUE TITLE
Open ttyUSB device in Ubuntu (list pos empty)

### ISSUE THREAD

**Issue by ghvau** [jczic/ESP32-MPY-Jama#33]
![image](https://user-images.githubusercontent.com/125656550/229040099-cb0f5914-0775-4715-9dbd-0466b743e633.png)

Inside device selection there is an EMPTY position which represent the connected device.
dmesg: usb 2-1.2: cp210x converter now attached to ttyUSB0
If selected the device will connected and is usable.

Ubuntu 22.04
Jama just downloaded

**Comment by jczic** [comment]
Hi @ghvau, do you have download from binaries or from repository sources?
I'll check that.

**Comment by jczic** [comment]
Ok that's works thanks

**Comment by ghvau** [comment]
Problem was size or character inside port description.

See private mail

**Comment by jczic** [comment]
Well @ghvau, it's fixed on commit : https://github.com/jczic/ESP32-MPY-Jama/commit/9603f12a1870eee4a723d3d990ca495f267d57e4
:)

**Comment by ghvau** [comment]
Thanks, solved !
