### ISSUE TITLE
Boot configuration (some wifi connection) get problems (Ubuntu)

### ISSUE THREAD

**Issue by ghvau** [jczic/ESP32-MPY-Jama#34]
![image](https://user-images.githubusercontent.com/125656550/229094656-2ed594c5-85eb-4d99-b6eb-e47fdeb04cbb.png)

Router1: b'NG-AP-ST', b'P\xe66\xc1\x0e\x10', 1, -71, 7, False 
Router2: b'Freifunk', b'\xd2\x95\x05I\xd48', 9, -86, 0, False

Testsequence:

I start with empty Boot config:
![image](https://user-images.githubusercontent.com/125656550/229094810-42a6bf50-d9e0-44f8-bea2-258decb416d2.png)

Set up connection Router2 via Network or Connect Wi-Fi:
Store icon appears (rotate clockwise) but nothing happens/stored !
The store icon stays permanent with clockwise move.
But connection established (can get NTP)
![image](https://user-images.githubusercontent.com/125656550/229094969-364b37bc-ad3d-4f88-9092-0f2f78a0550d.png)

I close the connection of Router2 and setup Router1
The Store icon appears and data can be stored !!!
![image](https://user-images.githubusercontent.com/125656550/229095272-f3f7475c-35e9-460a-a249-cfd57ceb1592.png)

After successful storing I can also (after close R1 and new setup Router2) store data ?!
But it seems be not the data of Router2.

When I start jamaBootCfg manually I can see always “Connecting Wi-Fi to "NG-AP-ST"... OK”,

**Comment by ghvau** [comment]
Ubuntu 22.04, github source code

**Comment by jczic** [comment]
Hi @ghvau and thank you for your feedback!
It was a bug and I fixed it right then and there.
It works now, thanks again. 👍🏻

**Comment by ghvau** [comment]
Thanks, solved!
