### ISSUE TITLE
Build/packaging sets lang to fr

### ISSUE THREAD

**Issue by andypiper** [jczic/ESP32-MPY-Jama#6]
Small observation :-) I noticed that the full screen option was in French on my Mac - I switched this in `Info.plist` inside the app bundle:

```xml
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
```

I guess this could be removed to default to the user's OS language.

**Comment by jczic** [comment]
Hi @andypiper, thank you, I've fixed that in my Mac bundle configuration :)
Have a nice day!
